# Generated by Django 3.2 on 2021-05-01 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist_app', '0008_auto_20210426_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auth.user'),
            preserve_default=False,
        ),
    ]
